# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-24 03:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipinfo',
            name='contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.ContractDetail', verbose_name='关联合同'),
        ),
        migrations.AddField(
            model_name='equipinfo',
            name='supllier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.SupplierInfo', verbose_name='厂商'),
        ),
        migrations.AlterField(
            model_name='equipinfo',
            name='_type',
            field=models.CharField(max_length=64, null=True, verbose_name='型号'),
        ),
        migrations.AlterField(
            model_name='equipinfo',
            name='remark',
            field=models.CharField(max_length=64, null=True, verbose_name='备注'),
        ),
    ]
