# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-24 05:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20200624_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectronicTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='equipinfo',
            name='depart',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app01.Department', verbose_name='使用部门'),
        ),
    ]
