# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-24 05:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20200624_1347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipinfo',
            old_name='_class',
            new_name='classes',
        ),
    ]
