# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-24 05:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20200624_1349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipinfo',
            old_name='_type',
            new_name='types',
        ),
    ]
