# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-24 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20200624_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipinfo',
            name='contract',
            field=models.FileField(null=True, upload_to='contract/', verbose_name='合同'),
        ),
    ]
