# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-24 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_auto_20200624_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmaint',
            name='service_type',
            field=models.IntegerField(choices=[(1, '保内维修'), (2, '过保厂家收费'), (3, '过保自行维修')], default=1, verbose_name='维修方式'),
        ),
    ]
