# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-24 08:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_equipmaint_service_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipmaint',
            old_name='_class',
            new_name='classes',
        ),
    ]
