# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-24 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_auto_20200624_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmaint',
            name='name',
            field=models.CharField(default='', max_length=32, verbose_name='设备名称'),
        ),
    ]
