# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-24 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_equipmaint_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmaint',
            name='SN',
            field=models.CharField(max_length=128, verbose_name='出厂编号'),
        ),
    ]
