# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-26 13:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_auto_20200624_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipAllot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='设备名称')),
                ('date', models.DateField(auto_now=True, verbose_name='调拔时间')),
                ('SN', models.CharField(max_length=32, verbose_name='设备出厂编码')),
                ('remark', models.CharField(max_length=64, verbose_name='备注')),
                ('classes', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app01.EquipClass', verbose_name='设备分类')),
                ('in_depart', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='in_part', to='app01.Department', verbose_name='调入部门')),
                ('out_depart', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='out_part', to='app01.Department', verbose_name='调出部门')),
            ],
        ),
    ]
