# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-26 14:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0012_equipscrap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipscrap',
            name='warranty',
        ),
    ]
