# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-27 01:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0013_remove_equipscrap_warranty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contractdetail',
            old_name='_class',
            new_name='classes',
        ),
    ]
