# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-27 01:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0014_auto_20200627_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractdetail',
            name='supplier',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app01.SupplierInfo', verbose_name='厂商'),
        ),
    ]
